language: c
install: wget https://raw.githubusercontent.com/samoht/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  - OCAML_VERSION=4.01   DEPOPTS="git cohttp"
  - OCAML_VERSION=latest DEPOPTS="git cohttp"
